[tools]

cmake = "4.4.3"
gh = "latest"
imagemagick = "latest"
python = "3.12.13"
rust = "latest"
uv = "latest"

"pipx:changes-semver" = "6"
"pipx:check-jsonschema" = "0"
"pipx:inseven-build-tools" = "1"

[env]

MISE_CACHE_DIR = "{{config_root}}/.mise/cache"
MISE_CONFIG_DIR = "{{config_root}}/.mise/config"
MISE_DATA_DIR = "{{config_root}}/.mise/data"
MISE_STATE_DIR = "{{config_root}}/.mise/state"

MISE_CARGO_HOME = "{{config_root}}/.mise/data/cargo"
MISE_RUSTUP_HOME = "{{config_root}}/.mise/data/rustup"

UV_CACHE_DIR = "{{config_root}}/.mise/cache/uv"

UV_PYTHON_PREFERENCE = "only-system"

[settings]

minimum_release_age_excludes = ["pipx:changes-semver", "pipx:inseven-build-tools"]
