[package]
name = "nezumi-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.5"
raylib = { version = "5.5", path = "raylib-rs/raylib" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"

[features]
drm = ["raylib/sdl"]
