[package]
name = "nezumi-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = { version = "5.5", features = ["sdl"], path = "raylib-rs/raylib" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
